-- Add sequential order number column to orders table
-- Run this SQL in your Supabase SQL Editor

-- Step 1: Add the order_number column with auto-increment starting from 1000
ALTER TABLE orders 
ADD COLUMN IF NOT EXISTS order_number INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000);

-- Step 2: Backfill existing orders with sequential numbers
-- This will continue from the highest existing order_number, or start at 1000 if none exist
DO $$
DECLARE
  rec RECORD;
  counter INT;
  max_existing INT;
BEGIN
  -- Find the highest existing order number
  SELECT COALESCE(MAX(order_number), 999) INTO max_existing FROM orders WHERE order_number IS NOT NULL;
  
  -- Start counter from the next number
  counter := max_existing + 1;
  
  -- Assign sequential numbers to orders without order_number
  FOR rec IN 
    SELECT id FROM orders WHERE order_number IS NULL ORDER BY created_at ASC
  LOOP
    UPDATE orders SET order_number = counter WHERE id = rec.id;
    counter := counter + 1;
  END LOOP;
END $$;

-- Step 3: Create an index for faster queries
CREATE INDEX IF NOT EXISTS idx_orders_order_number ON orders(order_number);

-- Verify the changes
SELECT id, order_number, customer_name, created_at 
FROM orders 
ORDER BY order_number DESC 
LIMIT 10;
